# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Avxctl < Formula
  desc ""
  homepage "https://github.com/aajolly/avxctl"
  version "0.4"

  on_macos do
    url "https://github.com/aajolly/avxctl/releases/download/v0.4/avxctl_0.4_darwin_all.tar.gz"
    sha256 "7e8c4047d2193618ae6bcb1c95a083b7ab22190ee151344feaa0214f5bd40c16"

    def install
      bin.install "avxctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aajolly/avxctl/releases/download/v0.4/avxctl_0.4_linux_arm64.tar.gz"
      sha256 "e1d13d20cba129a849a14d7146633425d2cb7d0f505e83acb8e9ad8d3800cc1f"

      def install
        bin.install "avxctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aajolly/avxctl/releases/download/v0.4/avxctl_0.4_linux_amd64.tar.gz"
      sha256 "70a2545e752cf758b824ca2b7fccac113f92deb87516db396e349b2f9a755c4d"

      def install
        bin.install "avxctl"
      end
    end
  end
end
