# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Avxctl < Formula
  desc ""
  homepage "https://github.com/aajolly/avxctl"
  version "0.3"

  on_macos do
    url "https://github.com/aajolly/avxctl/releases/download/v0.3/avxctl_0.3_darwin_all.tar.gz"
    sha256 "d5d620ce2752954e845f869c51755fbd9555feefde96dc40576718ec7f10f74e"

    def install
      bin.install "avxctl"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aajolly/avxctl/releases/download/v0.3/avxctl_0.3_linux_amd64.tar.gz"
      sha256 "b76e99b14da1fa3e7a571bc9bd0ee23784eec769a42fa4ffea821963fc6a2ce0"

      def install
        bin.install "avxctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aajolly/avxctl/releases/download/v0.3/avxctl_0.3_linux_arm64.tar.gz"
      sha256 "a24f97396d0a4015f50d6dc262829c547565930fd2733e9c35e7422a642e0ecb"

      def install
        bin.install "avxctl"
      end
    end
  end
end
