# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Avxctl < Formula
  desc ""
  homepage "https://github.com/aajolly/avxctl"
  version "0.5"

  on_macos do
    url "https://github.com/aajolly/avxctl/releases/download/v0.5/avxctl_0.5_darwin_all.tar.gz"
    sha256 "006414d7dd37d9d83e34efa500cf054e22f5c763b8db642a087ea8b6c6da9018"

    def install
      bin.install "avxctl"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aajolly/avxctl/releases/download/v0.5/avxctl_0.5_linux_arm64.tar.gz"
      sha256 "2fa96f2a9bb91ea55ca7d429e28031d1da874c6b3cb984bf67667f54f593e8b8"

      def install
        bin.install "avxctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aajolly/avxctl/releases/download/v0.5/avxctl_0.5_linux_amd64.tar.gz"
      sha256 "04e82fba880e6cb77f86a77eaf8081656335f48f0ecf329bcf1ca84fec1dc2ff"

      def install
        bin.install "avxctl"
      end
    end
  end
end
